name: Check Domain Availability

on:
  # 스케줄: 매일 한국 시간 오전 9시, 오후 9시
  # 한국 시간 (KST) = UTC + 9시간
  # 오전 9시 KST = 오전 0시 UTC
  # 오후 9시 KST = 오후 12시 UTC
  schedule:
    - cron: '0 0,12 * * *'
  
  # 수동 실행 가능
  workflow_dispatch:

jobs:
  check-domains:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Call CRON API
        run: |
          response=$(curl -s -L -w "\n%{http_code}" -X GET \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            ${{ secrets.APP_URL }}/api/check-domains)
          
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
          
          echo "HTTP Status: $http_code"
          echo "Response: $body"
          
          if [ "$http_code" != "200" ]; then
            echo "Error: API returned status $http_code"
            exit 1
          fi
      
      - name: Log completion
        if: success()
        run: |
          echo "✅ Domain check completed successfully at $(date)"
      
      - name: Log failure
        if: failure()
        run: |
          echo "❌ Domain check failed at $(date)"
